### ISSUE TITLE
error when run make_checkpoint.py

### ISSUE THREAD

**Issue by TTTJJJWWW** [carlini/audio_adversarial_examples#18] opened 2018-12-21 11:40 UTC
Hi!
 When i run "python3 make_checkpoint.py", i get errors like that:

WARNING:tensorflow:From make_checkpoint.py:60: calling import_graph_def (from tensorflow.python.framework.importer) with op_dict is deprecated and will be removed in a future version.
Instructions for updating:
Please file an issue at https://github.com/tensorflow/tensorflow/issues if you depend on this feature.
ERROR: The decoder library file does not exist. Make sure you have downloaded or built the native client binaries and pass the appropriate path to the binaries in the --decoder_library_path parameter.
This value should be small 0.0

what is the problem? and how to fix it?

**Comment by TTTJJJWWW** [comment] 2018-12-21 12:47
When i run "python3 attack.py --in sample.wav --target "example" --out adversarial.wav"

pydub was not loaded, MP3 compression will not work
source dB 90.3087329864502
ERROR: The decoder library file does not exist. Make sure you have downloaded or built the native client binaries and pass the appropriate path to the binaries in the --decoder_library_path parameter.
Traceback (most recent call last):
  File "/home/tjw/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/tjw/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/tjw/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
	 [[Node: save/RestoreV2/_11 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_16_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "attack.py", line 387, in <module>
    main()
  File "attack.py", line 365, in main
    l2penalty=args.l2penalty)
  File "attack.py", line 127, in __init__
    saver.restore(sess, "models/session_dump")
  File "/home/tjw/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1802, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/tjw/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/tjw/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/tjw/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/tjw/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
	 [[Node: save/RestoreV2/_11 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_16_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

How can i make it work?

**Comment by TTTJJJWWW** [comment] 2018-12-21 13:25
@carlini  Hi!
Now i try to generate adversarial examples and Ignore this problem （ERROR: The decoder library file does not exist. Make sure you have downloaded or built the native client binaries and pass the appropriate path to the binaries in the --decoder_library_path parameter）.
when i try "python3 attack.py --in sample.wav --target "example" --out adversarial.wav", the result is "xample" with out "e"
Then i try "python3 attack.py --in sample.wav --target "test" --out adversarial.wav", the result is "es" without "t..t".
Did i use the code on a wrong way? Why it have this problem? Look forward to your reply. Thanks!

**Comment by carlini** [comment] 2018-12-21 14:51
Okay, so it looks at least like you're getting the code to run properly. I'll try to make it clear those warnings aren't important.

As for why the output isn't working correctly, are you using the sample that's included in the git repository and letting it run for the 5000 iterations? If you want to let it be faster, you can set the learning rate to 100 and use fewer iterations.

**Comment by TTTJJJWWW** [comment] 2018-12-21 14:59
@carlini Thanks for your reply! Yes, I use the sample that's included in the git repository(contain "a"? or nothing), and I have not modified the "attack.py" until now(using the default learning rate).
You mean that change the learning rate will make output be correct?

**Comment by carlini** [comment] 2019-01-28 16:18
Sorry for not responding--did you ever figure this out?

**Comment by htZhang25** [comment] 2019-03-06 13:01
Sorry to bother,I got the same result with you.And it seems there is always some(one or two) letters lost.Like that I got "meanwile" when targeting "meanwhile",got  "go shoping" when targeting "go shopping".Do you have an idea about that? How to improve it?

**Comment by carlini** [comment] 2019-03-06 15:17
Thanks for letting me know about this. I'll try to reproduce the issue tomorrow and see what's going on.

**Comment by carlini** [comment] 2019-03-09 06:08
Looks like just passing --lr 10 will fix it for the wave file uploaded to the repo. Does this work for you?

**Comment by htZhang25** [comment] 2019-03-13 02:16
No，I still got “examle ” while i run :python attack.py --in sample.wav --target "example" --out adversarial.wav --lr 10 --iterations 5000

**Comment by carlini** [comment] 2019-03-13 03:32
Does it not work in that the final generated example is misclassified? Or does it not work in that along the way it doesn't believe it has succeeded?

**Comment by htZhang25** [comment] 2019-03-13 07:23
Sorry,i dont know How can i say that i've already got the correct adversarial audio example,in spite of the wrong recognition of DeepSpeech? What should be the criter to infer this?     All i know is that finally i got "examle" corresponding to "# Here we print the strings that are recognized.", which is the decoder result of DeepSpeech i think.

**Comment by htZhang25** [comment] 2019-03-13 07:28
Sorry,i dont know How can i say that i've already got the correct adversarial audio example. Isn't the  result of the decoder should be the criter to infer this? I got "examle" corresponding to "# Here we print the strings that are recognized.", which is the decoder result of DeepSpeech i think. I'm not quite getting across you ?

**Comment by htZhang25** [comment] 2019-03-13 07:36
Sorry,i dont know how i can say that i've already got the correct adversarial audio example. Isn't the result of the decoder the criter to infer this? I got "examle" corresponding to "# Here we print the strings that are recognized.", which is the decoder result of DeepSpeech i think. I'm not quite getting across your  second expression ?For the whole iterations,it work,but i can't get the perfect phrase the same as target phrase.

**Comment by htZhang25** [comment] 2019-03-13 07:56
To supplement，I did't run the DeepSpeech using the generated example as input.

**Comment by carlini** [comment] 2019-03-13 14:33
Alright, thanks, let me take a look then. Maybe it's quantizing that's breaking things.

**Comment by carlini** [comment] 2019-03-14 04:07
Hmm, I still can't reproduce this... Mine seems to work as expected.

Can you copy and paste the whole execution that you're running, both the attack.py invocation as well as everything it's doing, along with running classify.py? You can just run with 500 iterations to make it shorter.

**Comment by TTTJJJWWW** [comment] 2019-03-14 05:03
@carlini @htZhang25 Hi！ I found that using a real audio(contain real words) will make results better. So I use the real audio from voice dataset (16Hz). But I don't know why for now.

**Comment by carlini** [comment] 2019-08-07 16:50
make_checkpoint.py no longer is necessary; closing this issue.

**Closed as completed by carlini** 2019-08-07 16:50 UTC
